# Generated by Django 2.2.6 on 2019-10-09 15:30

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='images/')),
                ('cv', models.FileField(upload_to='documents/')),
                ('specialize', models.CharField(blank=True, max_length=100)),
                ('about', models.TextField(blank=True)),
                ('skils', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=120, size=10)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('twitter_profile', models.URLField(blank=True)),
                ('facebook_profile', models.URLField(blank=True)),
                ('google_profile', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('weblink', models.URLField(blank=True)),
                ('descriptions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('descriptions', models.TextField(blank=True)),
            ],
        ),
    ]
